[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "python-examples"
version = "0.1.0"
description = "Algorithms and systems examples repo"
readme = "README.md"
requires-python = ">=3.8"

dependencies = [
    "numpy>=1.23.5",
]

[tool.setuptools]
package-dir = {"" = "."}

[tool.setuptools.packages.find]
where = ["."]
include = ["Algorithms*", "LLMs*"]

[dependency-groups]
dev = [
    "pre-commit>=3.5.0",
    "pytest-cov>=4.0,<5",
]
